# Generated by Django 2.2.1 on 2019-05-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('sex', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
